/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.erfangc.marketmonitor.fundamentals

import com.github.doyaaaaaken.kotlincsv.dsl.csvReader
import com.ma.io.MongoDB.fundamentals
import com.ma.fundamentals.models.Fundamental
import com.mongodb.client.model.Indexes
import com.vhl.blackmo.grass.dsl.grass

@ExperimentalStdlibApi
private fun loadFundamentals() {

    val fileName = "/Users/erfangchen/Downloads/SHARADAR_SF1_0902195e140925ca23756cd43d9f89ae.csv"
    val fundamentals = fundamentals

    fundamentals.drop()
    fundamentals.createIndex(Indexes.ascending(Fundamental::datekey.name))
    fundamentals.createIndex(Indexes.compoundIndex(Indexes.hashed(Fundamental::ticker.name)))

    csvReader()
            .open(fileName) {
                val seq = readAllWithHeaderAsSequence()
                grass<Fundamental>()
                        .harvest(seq)
                        .forEachIndexed { idx, fundamental ->
                            val result = fundamentals.insertOne(fundamental)
                            println(
                                    "Inserted" +
                                            " ticker=${fundamental.ticker}" +
                                            " idx=$idx" +
                                            " dimension=${fundamental.dimension} " +
                                            " datekey=${fundamental.datekey}" +
                                            " _id=${result.insertedId}"
                            )
                        }
            }

}
