openapi: 3.0.0
info:
  title: Market Monitor
  description: Market Monitor
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /:
    get:
      operationId: getCrossSectionals
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/CrossSectional'

components:
  schemas:
    CrossSectional:
      properties:
        date:
          type: string
          format: date
        positiveNegativeRatio:
          type: number
          format: double
        pe:
          type: number
          format: double
        peCount:
          type: integer
        totalMarketCap:
          type: number
          format: double
